version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - pg_db
    links: 
        - pg_db
    networks:
    - mynet
  pg_db:
    container_name: pg_db
    image: postgres:13.3
    environment:
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGDATABASE=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "pg_isready", "--quiet"]
        interval: 30s
        timeout: 10s
        retries: 10
    networks:
    - mynet

volumes:
  pgdata: {}

networks:
  mynet:
    driver: bridge